### ISSUE TITLE
Backtracking tracker

### ISSUE THREAD

**Issue by ebeshero** [FrankensteinVariorum/collationWorkspace#22]
@nhammer514 
This is the Backtracking assignment with the goal to get us a long block of connected collation units for @Yuying-Jin to transform. 

- [x] #23

- [x] Begin by checking out a new `nlh-backtracking` branch. 
- [x] Next, change every  `Collation_C??-complete.xml` to `Collation_C??-old.xml`
- [x] Run the fancy new coll.sh over all the units. Possibly overnight. (Or do just a few of them at a time.)

When collation completes, start viewing these with Schematron and in the oXygen diff tool.

Tick off the collation units as you complete reviewing the new collation on them, and add comments about the state of the new collation. Comments don't need to be detailed in this issue: just note on a high level whether you see:
* Unresolved issues
* Okay / improved--ready to go

Add more detailed comments as needed for the Readme in the collation unit.
When you add more comments to a Readme, link the Readme here. 

- [x] C11 Dr. B and Yuying did this.
- [x] C12 No visible differences (1 Warning, 25 Info)
- [x] C13 No visible differences (6 Warnings, 152 Info)
- [x] C14 In total 707 differences (6 Warnings, 163 Info)
- [x] C15 In total 244 differences (6 Warnings, 160 Info)
- [x] C16 In total 774 differences (84 Info)
- [x] C17 In total 229 differences (5 Warnings, 35 Info)
- [x] C18 In total 468 differences (1 Warning 17 Info)
- [x] C19 In total 5 differences (1 Warning, 55 Info)
- [x] C20 In total 121 differences (5 Warning, 49 Info)
- [x] C21 (new)
=============== Can you get this far by Tuesday May 30?
- [ ] C22
- [ ] C23 (new)
- [ ] C24
